### ISSUE TITLE
Warren County: AttributeError: 'WarrenMortgageInfo' object has no attribute 'headers'

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/property_project_ohio#130]
```
Traceback (most recent call last):
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
(self._dns_host, self.port), self.timeout, **extra_kw)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
raise err
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
sock.connect(sa)
TimeoutError: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
self._validate_conn(conn)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
conn.connect()
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
conn = self._new_conn()
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x111cd29b0>: Failed to establish a new connection: [Errno 60] Operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
timeout=timeout
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
_stacktrace=sys.exc_info()[2])
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oh3laredo.fidlar.com', port=443): Max retries exceeded with url: /OHWarren/Scrap.WebService.Ava/breeze/breeze/Search (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x111cd29b0>: Failed to establish a new connection: [Errno 60] Operation timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/Lucia/Code/Blue/property_project_ohio/scrapyohio/scrapyohio/scraper_helpers/warren_mortgage.py", line 89, in download_list_of_recorder_data_items
response = requests.request("POST", self.WARREN_INITIAL_SEARCH, data=payload, headers=self.HEADERS)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/requests/api.py", line 60, in request
return session.request(method=method, url=url, **kwargs)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='oh3laredo.fidlar.com', port=443): Max retries exceeded with url: /OHWarren/Scrap.WebService.Ava/breeze/breeze/Search (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x111cd29b0>: Failed to establish a new connection: [Errno 60] Operation timed out',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "manage.py", line 22, in 
execute_from_command_line(sys.argv)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/init.py", line 381, in execute_from_command_line
utility.execute()
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/init.py", line 375, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
self.execute(*args, **cmd_options)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
output = self.handle(*args, **options)
File "/Users/Lucia/Code/Blue/property_project_ohio/propertyrecords/management/commands/warren-mort.py", line 10, in handle
a.download_mortgage_info()
File "/Users/Lucia/Code/Blue/property_project_ohio/scrapyohio/scrapyohio/scraper_helpers/warren_mortgage.py", line 182, in download_mortgage_info
self.identify_most_recent_mortage_for_each()
File "/Users/Lucia/Code/Blue/property_project_ohio/scrapyohio/scrapyohio/scraper_helpers/warren_mortgage.py", line 145, in identify_most_recent_mortage_for_each
recorder_data = self.download_list_of_recorder_data_items(trimmed_parcel_number)
File "/Users/Lucia/Code/Blue/property_project_ohio/scrapyohio/scrapyohio/scraper_helpers/warren_mortgage.py", line 92, in download_list_of_recorder_data_items
print("ConnectionError exception raised. Payload: ", payload, " headers: ", self.headers)
AttributeError: 'WarrenMortgageInfo' object has no attribute 'headers'
```

**Comment by ludstuen90** [comment]
I believe this should be fixed with https://github.com/ludstuen90/property_project_ohio/commit/8f2685c157b5d4ac8c73e7c7dc5da94d2c5b93e4#diff-27fd020cfcbcb8086d37bb68622c48db

**Comment by ludstuen90** [comment]
Closing this ticket, per comment above.
