### ISSUE TITLE
Warren County: requests.exceptions.ConnectionError: ('Connection aborted.', LineTooLong('got more than 65536 bytes when reading header line',))

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/property_project_ohio#131]
```
Found mortgage date of $ 344000.0 date 2016-09-19 12:09:04 on account number: 1131898
Found mortgage date of $ 105000.0 date 2016-11-29 09:43:04 on account number: 6150073
Traceback (most recent call last):
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
six.raise_from(e, None)
File "", line 2, in raise_from
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
httplib_response = conn.getresponse()
File "/Users/Lucia/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
response.begin()
File "/Users/Lucia/anaconda3/lib/python3.6/http/client.py", line 321, in begin
self.headers = self.msg = parse_headers(self.fp)
File "/Users/Lucia/anaconda3/lib/python3.6/http/client.py", line 208, in parse_headers
raise LineTooLong("header line")
http.client.LineTooLong: got more than 65536 bytes when reading header line

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
timeout=timeout
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
_stacktrace=sys.exc_info()[2])
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
raise six.reraise(type(error), error, _stacktrace)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
raise value.with_traceback(tb)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
chunked=chunked)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
six.raise_from(e, None)
File "", line 2, in raise_from
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
httplib_response = conn.getresponse()
File "/Users/Lucia/anaconda3/lib/python3.6/http/client.py", line 1331, in getresponse
response.begin()
File "/Users/Lucia/anaconda3/lib/python3.6/http/client.py", line 321, in begin
self.headers = self.msg = parse_headers(self.fp)
File "/Users/Lucia/anaconda3/lib/python3.6/http/client.py", line 208, in parse_headers
raise LineTooLong("header line")
urllib3.exceptions.ProtocolError: ('Connection aborted.', LineTooLong('got more than 65536 bytes when reading header line',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "manage.py", line 22, in 
execute_from_command_line(sys.argv)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/init.py", line 381, in execute_from_command_line
utility.execute()
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/init.py", line 375, in execute
self.fetch_command(subcommand).run_from_argv(self.argv)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
self.execute(*args, **cmd_options)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
output = self.handle(*args, **options)
File "/Users/Lucia/Code/Blue/property_project_ohio/propertyrecords/management/commands/warren-mort.py", line 10, in handle
a.download_mortgage_info()
File "/Users/Lucia/Code/Blue/property_project_ohio/scrapyohio/scrapyohio/scraper_helpers/warren_mortgage.py", line 196, in download_mortgage_info
self.identify_most_recent_mortage_for_each()
File "/Users/Lucia/Code/Blue/property_project_ohio/scrapyohio/scrapyohio/scraper_helpers/warren_mortgage.py", line 175, in identify_most_recent_mortage_for_each
self.download_mortgage_detail({prop_to_parse: most_recent_item})
File "/Users/Lucia/Code/Blue/property_project_ohio/scrapyohio/scrapyohio/scraper_helpers/warren_mortgage.py", line 144, in download_mortgage_detail
mortgage_amount = self.retrieve_document_details(mortgage_info['Id'])
File "/Users/Lucia/Code/Blue/property_project_ohio/scrapyohio/scrapyohio/scraper_helpers/warren_mortgage.py", line 126, in retrieve_document_details
response = s.request("POST", self.WARREN_DOCUMENT_DETAIL, data=payload, headers=self.HEADERS)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
resp = self.send(prep, **send_kwargs)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
r = adapter.send(request, **kwargs)
File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', LineTooLong('got more than 65536 bytes when reading header line',))
```

**Comment by ludstuen90** [comment]
Workaround for this is to use `python infinite.py warren-mort`
