### ISSUE TITLE
'response_json' referenced before assignment

### ISSUE THREAD

**Issue by walinchus** [ludstuen90/property_project_ohio#137]
ConnectionEror exception raised, unable to print all attributes
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/Users/Lucia/Code/Blue/property_project_ohio/propertyrecords/management/commands/warren-mort.py", line 10, in handle
    a.download_mortgage_info()
  File "/Users/Lucia/Code/Blue/property_project_ohio/scrapyohio/scrapyohio/scraper_helpers/warren_mortgage.py", line 185, in download_mortgage_info
    self.identify_most_recent_mortage_for_each()
  File "/Users/Lucia/Code/Blue/property_project_ohio/scrapyohio/scrapyohio/scraper_helpers/warren_mortgage.py", line 158, in identify_most_recent_mortage_for_each
    recorder_data = self.download_list_of_recorder_data_items(trimmed_parcel_number)
  File "/Users/Lucia/Code/Blue/property_project_ohio/scrapyohio/scrapyohio/scraper_helpers/warren_mortgage.py", line 109, in download_list_of_recorder_data_items
    if response_json.get('Msg', '') == 'Session is invalid':
UnboundLocalError: local variable 'response_json' referenced before assignment
(env) Daddy-Mac-418:property_project_ohio Lucia$

**Comment by walinchus** [comment]
Does this just mean we've hit the end? 

Lucia's Dashboard of Warren Scraping Progress
Number of Warren County properties scanned for mortgage information: 70781 (70%)
Number of Warren County properties with mortgage information: 70692 ( 70%)
Total number of Warren County properties: 100459

(Before it would say "scraper finished."

**Comment by ludstuen90** [comment]
@walinchus Ay, we haven't scanned all articles because the number of props scanned for mortgage info is still at 70%. It just means we hit a property and weren't able to scan information for it. 

It looks like the scanner stopped running. If we run it inside of the infinite script, it should start back up again. `python infinite.py warren-mort`

I see what's going on in the code, and I can put in a fix. Also, it looks like Django has a security vulnerability. (Doesn't affect us since we're not running this site in public. Still, not a bad idea to update) 

I can make a quick fix for the security updates and to catch this

**Comment by ludstuen90** [comment]
@walinchus All fixed, to download updates: 
`git pull origin master`
`pip install -r requirements.txt` (from the same place as the requirements.txt file)
