### ISSUE TITLE
Warren-mort bug: Key Error in line 122

### ISSUE THREAD

**Issue by ludstuen90** [ludstuen90/property_project_ohio#94]
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/Lucia/Code/Blue/property_project_ohio/env/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/Users/Lucia/Code/Blue/property_project_ohio/propertyrecords/management/commands/warren-mort.py", line 10, in handle
    a.download_mortgage_info()
  File "/Users/Lucia/Code/Blue/property_project_ohio/scrapyohio/scrapyohio/scraper_helpers/warren_mortgage.py", line 149, in download_mortgage_info
    self.identify_most_recent_mortage_for_each()
  File "/Users/Lucia/Code/Blue/property_project_ohio/scrapyohio/scrapyohio/scraper_helpers/warren_mortgage.py", line 122, in identify_most_recent_mortage_for_each
    most_recent_item = utils.select_most_recent_mtg_item(recorder_data, self.DATE_FORMAT)
  File "/Users/Lucia/Code/Blue/property_project_ohio/propertyrecords/utils.py", line 274, in select_most_recent_mtg_item
    mtg_items = [item for item in recorder_data_dict['DocResults'] if item['DocumentType'] == 'MTG']
KeyError: 'DocResults'
```

**Comment by ludstuen90** [comment]
Fixed with PR: 
https://github.com/ludstuen90/property_project_ohio/pull/95
